version: 2
updates:
  # Update npm dependencies in the backend directory
  - package-ecosystem: 'npm'
    directory: /
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    open-pull-requests-limit: 10

  # Update npm dependencies in the client directory
  - package-ecosystem: 'npm'
    directory: /frontend
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    open-pull-requests-limit: 10

  # Update GitHub Actions workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 10
